### ISSUE TITLE
export environment variables defined in the image

### ISSUE THREAD

**Issue by fsouza** [tsuru/diaats#4]
Docker supports declaring environment variables in the Dockerfile, these environment variables are then available in containers created using the built image, and are also forwarded when Docker links two containers. Some services use this Docker feature to expose authentication information, and since diaats supports only host and port, it isn't possible to use any service that require authentication at the moment (in other words, diaats works _really_ well with memcached and non-authenticated Redis haha).

We could inspect these environment variables and make then available during bind. That would expand diaats availability to images such as [mysql](https://hub.docker.com/_/mysql/) and [postgres](https://hub.docker.com/_/postgres/).

**Comment by andrewsmedina** [comment]
+1
